import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './my.css'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionProviderWrapper from "@/components/sessionProviderWrapper";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Get me A chai - Fund your projects with chai",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <SessionProviderWrapper>
            <body className={`${geistSans.variable} ${geistMono.variable} text-white antialiased`}>
                <Navbar/>
                {children}
                <Footer/>
            </body>
            </SessionProviderWrapper>
        </html>
    );
}
